package com.stephen.bangbang;


public interface Constants {
    int TOKEN_EXPIRES_DAYS = 7;
    String AUTHORIZATION_HEADER = "Authorization";
    String CURRENT_USER_ID = "CURRENT_USER_ID";
    int JIGUANG_CLIENT_MAX_RETRY = 5;
    int JIGUANG_CLIENT_CONNECTION_TIME_OUT = 10 * 1000;
    boolean JIHUANG_CLIENT_IN_PRODUCTION = false;
    String FRIENDS_MAKE = "make";
    String FRIENDS_AGREE = "agree";
    String JPUSH_MESSAGE_ALLOPATRIC_LOGIN = "ALLOPATRIC_LOGIN";
    String JPUSH_MESSAGE_PASSWORD_CHANGED = "PASSWORD_CHANGED";
    String JPUSH_MESSAGE_MAKE_FRIEND = "MAKE_FRIEND";
    String JPUSH_MESSAGE_MAKE_FRIEND_AGREE = "AGREE";
}
